'use strict';

const TIPS = [
  // Anchor usage
  'Type `re call dentist, monday 9am` to set a reminder with a specific time.',
  '`done N` permanently deletes reminder N — use it once you\'ve handled it.',
  '`snooze N friday 3pm` reschedules any reminder in one shot from any note.',
  '`change N to new text` rewrites a reminder\'s body without losing its date.',
  '`pt` prefix stores a note in Private Thoughts — encrypted, password-protected.',
  '`ol` creates an open loop — it shows in every morning digest until you close it.',
  '`close N` resolves open loop #N and moves it to closed-loop history.',
  '`pi` is your reference shelf — permanent facts like addresses, meds, and history.',
  '`ls` creates a checklist note — great for packing lists and repeating routines.',
  'Add `@tag` at the end of any note to label it for quick filtering later.',
  '`wt` for work tasks, `pst` for personal tasks — keeps your lanes clean.',
  '`anc` type is for notes about Anchor itself — meta, but surprisingly useful.',
  '`ch` creates a claude-handoff note — stores session context for your next AI chat.',
  'Ask Anchor anything about your notes — it searches and synthesizes across all types.',
  '`snooze N` with no time defaults to one week from now.',
  'Notes added via email to anchor@thecasmas.com are auto-ingested every 30 minutes.',
  '`r` is the catch-all random type — for ideas that don\'t fit anywhere else.',
  '`wi` for work ideas, `pid` for personal ideas — capture the spark before it fades.',
  '`emp` type tracks employment notes — job history, comp changes, review notes.',
  'Open loops show in every morning digest until you explicitly close them.',
  '`rec` or `rcp` for recipes — keeps your kitchen wins out of the task noise.',
  'The AI toggle switches between local Rooster (Ollama) and the Anthropic API.',
  '`pp` is for personal projects; `pp ls` renders it as a checklist.',
  '`kw`, `zs`, `es` create notes tied to specific people in your life.',
  'The sync queue batches pending notes — sync when there\'s enough to analyze.',
  '`hpr` for health projects — good for tracking treatment plans over time.',
  'Use `cal` for calendar-adjacent notes that don\'t need a hard reminder.',
  '`wpw` stores a work password note — encrypted like private thoughts.',
  'The 7AM digest is your daily briefing — check it before your day starts.',
  'Multiple notes in one input? Separate them with a blank line between type prefixes.',

  // Productivity & life wisdom
  'Write it down. Memory is for thinking, not storing.',
  'A short pencil beats a long memory.',
  'Do the hardest thing first. Everything else gets easier after.',
  'Two-minute rule: if it takes less than two minutes, do it now.',
  'The best time to plant a tree was 20 years ago. The second best time is now.',
  'Slow is smooth. Smooth is fast.',
  'Done is better than perfect.',
  'You don\'t rise to your goals — you fall to your systems.',
  'What gets measured gets managed.',
  'Say no to protect your yes.',
  'Sleep is not a reward. It\'s maintenance.',
  'Eat real food. Not too much. Mostly plants. — Michael Pollan',
  'Walk more. It solves more problems than you think.',
  'Worrying is praying for what you don\'t want.',
  'Energy management matters more than time management.',
  'A good question is worth more than a fast answer.',
  'Teach what you know — you\'ll understand it better for having explained it.',
  'Your future self is watching. Make them proud.',
  'Comparison is the thief of joy. — Theodore Roosevelt',
  'Sunlight, movement, and connection: the three most underrated cures.',
  'Regret of action fades. Regret of inaction lingers.',
  'The man who chases two rabbits catches neither.',
  'Water the plants that matter. Let the weeds go.',
  'Repetition is the mother of skill.',
  'Most stress is future-focused. Most joy is present-focused.',
  'Never mistake motion for progress.',
  'Ask for help earlier. The cost is almost always lower than you think.',
  'Every expert was once a beginner who refused to quit.',
  'Build systems, not goals. Goals end. Systems continue.',
  'Be the person your dog thinks you are.',
  'Don\'t save the good dishes for a special occasion. Today is special enough.',
  'Automate the repeatable. Humanize the irreplaceable.',
  'Complexity is the enemy of execution.',
  'If everyone is responsible, no one is responsible.',
  'Clarity on what matters most is the rarest and most valuable productivity skill.',
  'The obstacle is the way. — Marcus Aurelius',
  'You can do anything, but not everything.',
  'A calm mind is a productive mind.',
  'Progress, not perfection.',
  'The best investment you can make is in yourself.',

  // Strange sayings
  '"The early bird gets the worm, but the second mouse gets the cheese."',
  '"All sunshine makes a desert." — Arab proverb',
  '"Smooth seas do not make skillful sailors."',
  '"A man who carries a cat by the tail learns something he can learn no other way." — Mark Twain',
  '"He who asks is a fool for five minutes. He who doesn\'t remains a fool forever."',
  '"When the wind of change blows, some build walls, others build windmills."',
  '"A ship in harbor is safe — but that\'s not what ships are for."',
  '"Never test the depth of a river with both feet."',
  '"The best time to fix a leaky roof is when the sun is shining."',
  '"Even a stopped clock is right twice a day."',
  '"You don\'t need to eat the whole ox to know the meat is tough."',
  '"The squeaky wheel gets the grease, but the wobbly wheel falls off."',
  '"When you\'re in a hole, stop digging."',
  '"The devil is in the details — but so is the divine."',
  '"Nature abhors a vacuum — and so does an open meeting agenda."',
  '"If you want to go fast, go alone. If you want to go far, go together." — African proverb',
  '"Not my circus, not my monkeys." — Polish proverb',
  '"The road to hell is paved with good intentions and insufficient documentation."',
  '"Every solution breeds new problems."',
  '"He who hesitates is lost — but he who rushes in is also often lost."',
  '"Good fences make good neighbors." — Robert Frost',
  '"The fish rots from the head down."',
  '"The nail that sticks up gets hammered down." — Japanese proverb',
  '"An ounce of prevention is worth a pound of cure." — Benjamin Franklin',
  '"Fortune favors the prepared mind." — Louis Pasteur',

  // IT & tech wisdom
  'Never edit production directly. Never.',
  'The three most dangerous words in IT: "It should work."',
  'There are two kinds of people: those who back up their data, and those who haven\'t lost it yet.',
  'Comments lie. Code doesn\'t. Write honest code.',
  '"Works on my machine" is not a deployment strategy.',
  'Never underestimate the bandwidth of a station wagon full of hard drives.',
  'The problem is rarely where the error message says it is.',
  'If you haven\'t tested your restore process, you don\'t have backups.',
  'Automate everything you do more than twice.',
  'Make it work, make it right, make it fast — in that order.',
  'Security through obscurity is neither.',
  'Naming things well is one of the hardest problems in computer science.',
  'Write code as if the next reader is a sleep-deprived version of yourself.',
  'The best monitoring tells you before the user does.',
  'Every "we\'ll fix it later" is a check your future self will cash.',
  'A good README saves more hours than a clever algorithm.',
  'The fastest code is the code that doesn\'t run.',
  'Document your process while it\'s fresh. You\'ll never remember it later.',
  'When in doubt, reboot. When not in doubt, also consider rebooting.',
  'Premature optimization is the root of all evil. — Donald Knuth',

  // Fun facts
  'Honey never spoils — archaeologists found 3,000-year-old honey in Egyptian tombs, still edible.',
  'A group of flamingos is called a flamboyance.',
  'Octopuses have three hearts, blue blood, and can taste with their arms.',
  'Cleopatra lived closer in time to the Moon landing than to the construction of the Great Pyramid.',
  'There are more possible chess games than atoms in the observable universe.',
  'A day on Venus is longer than a year on Venus.',
  'Bananas are botanically berries. Strawberries are not.',
  'Crows can recognize human faces and hold grudges for years.',
  'The dot over a lowercase "i" is called a tittle.',
  'Mammoths were still alive when the Great Pyramid was under construction.',
  'Sea otters hold hands while sleeping so they don\'t drift apart.',
  'A bolt of lightning is five times hotter than the surface of the sun.',
  'Sharks are older than trees — they\'ve been around for 450 million years.',
  'All clownfish are born male. The dominant one becomes female.',
  'Oxford University is older than the Aztec Empire.',
  'The unicorn is Scotland\'s national animal.',
  'Wombats are the only known animals to produce cube-shaped droppings.',
  'Butterflies taste with their feet.',
  'Every year, more people are injured by their own furniture than by sharks.',
  'The Great Wall of China is not visible from space with the naked eye — that\'s a myth.',
];

function getTip() {
  return TIPS[Math.floor(Math.random() * TIPS.length)];
}

module.exports = { getTip, TIPS };
