'use strict';
const fs          = require('fs');
const { execSync } = require('child_process');
const { db, decryptNote, getPending, getLastSync } = require('./db');

const BRIDGE_PATH  = '/bridge';
const SESSION_FILE = BRIDGE_PATH + '/md/session-latest.md';

// ── DB helpers ────────────────────────────────────────────────────────────────

function getOpenLoops() {
  return db.prepare(
    "SELECT * FROM notes WHERE status='processed' AND open_loops IS NOT NULL AND open_loops!='' ORDER BY created_at DESC LIMIT 10"
  ).all().map(decryptNote);
}

function getRecentWork(days = 7) {
  return db.prepare(
    "SELECT * FROM notes WHERE status='processed' AND type IN ('work','work-task','work-decision','work-idea','meeting') AND created_at >= datetime('now',?) ORDER BY created_at DESC LIMIT 15"
  ).all(`-${days} days`).map(decryptNote);
}

function getActiveReminders() {
  try {
    return db.prepare(
      "SELECT * FROM notes WHERE remind_at IS NOT NULL AND remind_at!='' ORDER BY remind_at ASC LIMIT 20"
    ).all().map(decryptNote);
  } catch { return []; }
}

// ── Generate markdown ─────────────────────────────────────────────────────────

function generateSessionMd() {
  const now      = new Date();
  const { count: pending } = getPending();
  const lastSync = getLastSync();
  const loops    = getOpenLoops();
  const work     = getRecentWork(7);
  const reminders = getActiveReminders();

  const tz   = { timeZone: 'America/New_York' };
  const lines = [];

  lines.push('# Anchor — Session Context');
  lines.push(`**Generated:** ${now.toLocaleString('en-US', tz)}`);
  lines.push(`**Pending notes:** ${pending} | **Last sync:** ${lastSync ? lastSync.toLocaleString('en-US', tz) : 'Never'}`);
  lines.push('');

  if (reminders.length) {
    lines.push('## 🔔 Active Reminders');
    for (const n of reminders) {
      const num = n.remind_num ? `${n.remind_num})` : '•';
      const due = n.remind_at
        ? ` — due ${new Date(n.remind_at).toLocaleString('en-US', tz)}`
        : '';
      const sent = n.remind_sent ? ' ✓sent' : '';
      lines.push(`${num} ${(n.formatted || '').substring(0, 100)}${due}${sent}`);
    }
    lines.push('');
  } else {
    lines.push('## 🔔 Active Reminders');
    lines.push('None set yet.');
    lines.push('');
  }

  if (loops.length) {
    lines.push('## 🔁 Open Loops');
    for (const n of loops) {
      lines.push(`• [${n.type}] ${(n.open_loops || '').substring(0, 120)}`);
    }
    lines.push('');
  }

  if (work.length) {
    lines.push('## 💼 Recent Work Notes (7 days)');
    for (const n of work) {
      const d = new Date(n.created_at).toLocaleDateString('en-US', tz);
      lines.push(`• [${n.type}] ${d} — ${(n.formatted || '').substring(0, 120)}`);
    }
    lines.push('');
  }

  lines.push('## 📋 Working With Anchor');
  lines.push('- anchor.thecasmas.com — main UI');
  lines.push('- Commands (type in Add Note box, then Sync Now):');
  lines.push('  - `done 47` — resolves reminder 47, deletes it');
  lines.push('  - `snooze 4` — pushes reminder 4 out 1 week');
  lines.push('  - `snooze 4 10am` — 1 week from now at 10am');
  lines.push('  - `snooze 4 friday` or `snooze 4 jan 5 10pm` — specific time');
  lines.push('  - `change 4 to dentist thursday 3pm` — updates content + time');
  lines.push('  - Multiple in one note: `done 47, snooze 4 friday`');
  lines.push('- Reminder numbers are permanent — gaps are fine');
  lines.push('- Sync Bridge button: pulls latest from git + pushes this file');
  lines.push('');
  lines.push('---');
  lines.push('*Auto-generated by Anchor. Updates on every Sync Bridge or 7AM cron.*');

  return lines.join('\n');
}

// ── Git ops ───────────────────────────────────────────────────────────────────

const GIT_ENV = {
  ...process.env,
  GIT_AUTHOR_NAME:    'Anchor',
  GIT_AUTHOR_EMAIL:   'anchor@thecasmas.com',
  GIT_COMMITTER_NAME: 'Anchor',
  GIT_COMMITTER_EMAIL:'anchor@thecasmas.com'
};

function gitExec(cmd, cwd = BRIDGE_PATH) {
  return execSync(cmd, { cwd, env: GIT_ENV }).toString().trim();
}

function pullBridge() {
  try {
    const before = gitExec('git rev-parse HEAD');
    try { gitExec('git checkout -- .'); } catch (_) {} // discard any local edits so pull never conflicts
    const out    = gitExec('git pull');
    const after  = gitExec('git rev-parse HEAD');
    const changed = before !== after;
    let anchorFiles = [];
    if (changed) {
      const diff = gitExec(`git diff --name-only ${before} ${after}`);
      anchorFiles = diff.split('\n').filter(f => f.startsWith('anchor/') && f !== '');
    }
    console.log('[session] git pull:', out);
    return { ok: true, changed, anchorFiles, output: out };
  } catch (e) {
    console.error('[session] git pull failed:', e.message);
    return { ok: false, error: e.message };
  }
}

function pushSessionMd() {
  try {
    const content = generateSessionMd();
    fs.writeFileSync(SESSION_FILE, content, 'utf8');
    gitExec('git add md/session-latest.md');
    try {
      gitExec('git commit -m "anchor: auto-update session-latest.md"');
      gitExec('git push');
      console.log('[session] pushed session-latest.md');
    } catch (e) {
      if (e.message && e.message.includes('nothing to commit')) {
        console.log('[session] session-latest.md unchanged, no push needed');
        return { ok: true, note: 'no changes' };
      }
      throw e;
    }
    return { ok: true };
  } catch (e) {
    console.error('[session] push failed:', e.message);
    return { ok: false, error: e.message };
  }
}

module.exports = { generateSessionMd, pushSessionMd, pullBridge };
